import { jsPDF } from "jspdf";
import type { AuditResult } from "./types";

function hostname(u: string): string {
  try {
    return new URL(u).hostname.replace(/^www\./, "");
  } catch {
    return "report";
  }
}

// jsPDF's standard fonts only support Latin-1. Smart quotes, em-dashes, emoji,
// etc. make it fall back to a broken 2-byte mode (letters render with extra
// spaces), so normalize text to plain ASCII before writing it to the PDF.
function pdfText(s: string): string {
  return s
    .replace(/[‘’‚‛]/g, "'")
    .replace(/[“”„‟]/g, '"')
    .replace(/[–—]/g, "-")
    .replace(/…/g, "...")
    .replace(/[·•]/g, "-")
    .replace(/ /g, " ")
    .replace(/ /g, " ")
    .replace(/[^\x20-\x7E\n]/g, (c) => (c === " " ? " " : ""));
}

/**
 * Render the full audit as a Markdown document, in the order findings were
 * recorded (no grouping). Pass `images` (screenshotId -> base64) to embed the
 * evidence inline — used for on-screen display, omitted for the lean export.
 */
export function toMarkdown(
  r: AuditResult,
  opts: { images?: Map<string, string> } = {},
): string {
  const out: string[] = [];
  out.push(`# FreshEyes audit — ${hostname(r.url)}`, "");
  out.push(`**URL:** ${r.url}`, "");
  out.push(
    `**Status:** ${r.status} · **Steps:** ${r.steps} · **Findings:** ${r.findings.length}`,
    "",
  );
  out.push(`## Summary`, "", r.summary || "—", "");
  out.push(`## Findings`, "");
  if (r.findings.length === 0) out.push("No friction found. 🎉", "");

  r.findings.forEach((f, i) => {
    const tags = [f.severity.toUpperCase(), f.category].filter(Boolean).join(" · ");
    out.push(`### ${i + 1}. ${f.title}`);
    out.push(`_${tags}_`, "");
    out.push(f.description, "");
    out.push(`**Fix:** ${f.fix}`);
    if (f.url) out.push("", `**Where:** ${f.url}`);
    const b64 = f.screenshot ? opts.images?.get(f.screenshot) : undefined;
    if (b64) out.push("", `![evidence](data:image/png;base64,${b64})`);
    else if (f.screenshot) out.push("", `**Evidence:** ${f.screenshot}`);
    out.push("");
  });

  out.push("---", "_Generated by FreshEyes_");
  return out.join("\n");
}

function triggerDownload(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function downloadMarkdown(r: AuditResult) {
  // Lean export (no embedded base64 images) so the .md stays small.
  triggerDownload(`fresheyes-${hostname(r.url)}.md`, toMarkdown(r), "text/markdown");
}

/** Render the full audit as a paginated PDF (recorded order, no grouping). */
export function downloadPdf(r: AuditResult) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const M = 48;
  const W = doc.internal.pageSize.getWidth() - M * 2;
  const H = doc.internal.pageSize.getHeight();
  let y = M;

  const ensure = (h: number) => {
    if (y + h > H - M) {
      doc.addPage();
      y = M;
    }
  };
  const write = (
    text: string,
    size: number,
    opts: { bold?: boolean; color?: [number, number, number]; gap?: number } = {},
  ) => {
    doc.setFont("helvetica", opts.bold ? "bold" : "normal");
    doc.setFontSize(size);
    doc.setTextColor(...(opts.color ?? [24, 24, 27]));
    for (const line of doc.splitTextToSize(pdfText(text), W) as string[]) {
      ensure(size * 1.45);
      doc.text(line, M, y);
      y += size * 1.45;
    }
    if (opts.gap) y += opts.gap;
  };

  write("FreshEyes audit", 20, { bold: true });
  write(r.url, 10, { color: [37, 99, 235], gap: 2 });
  write(
    `Status: ${r.status}   ·   Steps: ${r.steps}   ·   Findings: ${r.findings.length}`,
    9,
    { color: [113, 113, 122], gap: 10 },
  );

  write("Summary", 14, { bold: true, gap: 2 });
  write(r.summary || "—", 11, { gap: 12 });

  write("Findings", 14, { bold: true, gap: 4 });
  if (r.findings.length === 0) write("No friction found.", 11);
  r.findings.forEach((f, i) => {
    y += 6;
    write(
      `${i + 1}. [${f.severity.toUpperCase()}${f.category ? ` · ${f.category}` : ""}] ${f.title}`,
      12,
      { bold: true },
    );
    write(f.description, 10, { gap: 2 });
    write(`Fix: ${f.fix}`, 10, { color: [37, 99, 235] });
    if (f.url) write(`Where: ${f.url}`, 9, { color: [113, 113, 122] });
  });

  doc.save(`fresheyes-${hostname(r.url)}.pdf`);
}
